name: Java CI Action
description: Build, test, and generate coverage

inputs:
  java-version:
    required: true
    default: '17'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin

    - name: Build and verify
      run: mvn clean verify
      shell: bash
