Upper:
str="GanEsH"
print(str.upper())..I/p
GANESH...O/p
lower:
print(str.lower())..I/p
ganesh...O/p
captialize:
print(str.captialize())..I/p
Ganesh...O/p
title:
print(str.title())..I/p
Ganesh..O/p
swapcase:
print(str.swapcase())..I/p
gANeSh..O/p
